license = "Apache-2.0"

[[mods]]
modId = "blazesdl_api"
version = "${version}"
displayName = "BlazeSDL API"
description = "API for BlazeSDL."
license = "Apache-2.0"
authors = "fifth_light"

[[dependencies.blazesdl_api]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "CLIENT"
