modLoader = "javafml"
loaderVersion = "[1,)"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}_vanilla"
version="${version}"
displayName="${name-vanilla}"
displayURL="${home_page}"
logoFile = "icon.png"
authors="fifth_light"
description='''${description-vanilla}'''

[[dependencies.${mod_id}_vanilla]]
modId="minecraft"
mandatory=true
versionRange="[1.21.2,)"
ordering="NONE"
side="CLIENT"
