modLoader = "javafml"
loaderVersion = "[1,)"
license = "${license}"
issueTrackerURL = "${issue_tracker}"

[[mods]]
modId = "combine_common"
version = "${version}"
displayName = "Combine common"
displayURL = "${home_page}"
logoFile = "icon.png"
authors = "fifth_light"
description = "${description}"

[[dependencies.combine_common]]
modId = "minecraft"
type = "required"
ordering = "NONE"
side = "CLIENT"

[[dependencies.combine_common]]
modId = "kotlinforforge"
type = "required"
ordering = "NONE"
side = "CLIENT"
